# Generated by Django 5.1.6 on 2025-02-06 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='nome',
            new_name='name',
        ),
    ]
