# Generated by Django 5.1.6 on 2025-02-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heroes", "0002_alter_heroes_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heroes",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
