# Generated by Django 5.1.6 on 2025-02-14 17:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heroes", "0005_alter_heroes_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heroes",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
